### PR TITLE
Add smooth scroll to page when clicking on header elements

### LINKED ISSUE #1: UI improvements to animate the scroll
When clicked on the UI elements in the header, scroll function should be animated. Any suggestions are welcome.

### PR DESCRIPTION
**Pull request by Alexius08**
Resolves #1 for the latest browsers.

Another approach is available if support for older browsers is needed.

### CODE REVIEW

**Comment by vishva-karma** [comment]
@Alexius08 Please include the support for older browsers too. That will be great.

**Comment by Alexius08** [comment]
Just pushed a JS-based smooth scroll function. The function would run in cases where the CSS-based approach don't work.

**Comment by vishva-karma** [comment]
That was quick and great. I will have a look at it and will close the merge.

**Comment by vishva-karma** [comment]
@Alexius08 If I understood it right, the new solution with jquery should work even on new browsers. isn't it??

**Comment by Alexius08** [comment]
Although the jQuery solution would work on both old and new browsers, it would only run for older browsers. The CSS solution will be used for the newer ones.

**Review by vishva-karma — APPROVED** [review]
Only tested on new browsers. But the code intended for old browser looks good.

**Pull request merged**
